import Head from 'next/head'
import MainPage from '../components/mainPage/MainPage'

const Index = () => {


  return (
    <>
      <Head>
        <title>Doctor`s World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <MainPage />

    </>
  )
}

export default Index
